import { Box } from '@chakra-ui/react'
import { NextPage } from 'next'
import * as React from 'react'
import AboutUs from '~/components/AboutUs'
import Footer from '~/components/Footer'
import Jumbotron from '~/components/Jumbotron'
import Navbar from '~/components/Navbar'
import SectionCard from '~/components/SectionCard'

const englishEducation = [
  {
    id: 1,
    heading: 'English Class',
    description:
      "The core program of English House held routinely every Sunday night (GMT+7) for English enthusiasts— focusing on different comprehension each week. Not only do our lecturers and co-lecturers train your English comprehensions, but also host games and quizzes! They will always be more than glad to guide you to learn English comfortably. Don't miss it out, folks!",
    img: '/images/english-class.png'
  },
  {
    id: 2,
    heading: 'Lecture Hall',
    description:
      'Requests for assistance or assessment may be submitted to this section, located in #lecture_hall. You will later be reached by the teacher(s) available, alongside members who wish to help you out as well. Requesting to get answers for your school exams or/and free written essays is forbidden, for we want to encourage you to do it on your own as much as you can first and foremost.',
    img: '/images/english-class.png'
  },
  {
    id: 3,
    heading: 'ProofReading',
    description: `
    You are welcome to request all sorts of proofreading, be it short or long paragraph(s), to our proofreaders! You may send your proofreading request to our proofreading text channel. They monitor and evaluate members' English practice for the OTD series weekly, by the way—oh psst, they are omnivores, but they won't bite you!
    `,
    img: '/images/english-class.png'
  }
]
const englishLearning = [
  {
    id: 1,
    heading: 'Book Club',
    description: `
    One of the main programs in English House, Book Club serves as the hub for bibliophiles and the not-so-bibliophiles! Book Club offers a relaxing, fun, light, and tension-free way to spend your evening by reading books together. From 'Dom Casmurro' to 'Dracula', our Curators would guide you as we delve deep into the narrative while actively practicing your listening and reading comprehension. What's the next book that we should read? YOU DECIDE!
You wouldn't want to miss it, Monday and Friday!
    `,
    img: '/images/english-class.png'
  },
  {
    id: 2,
    heading: 'IOTD',
    description: `Idiom practice is one of the most effective ways to advance your understanding of language to the next level! Express yourself with phrases, whether you're feeling fantastic, fancy, or even miserable! Idioms can grant you the power to break down the barrier of language ambiguity. Join us! Step up your linguistic game! Master the bizarre world of idioms only on English House Idiom of the day! #IOTD`,
    img: '/images/english-class.png'
  },
  {
    id: 3,
    heading: 'WOTD',
    description: `Expand your pool of vocabularies by practicing here. We provide new words each day with their details: definition, forms, synonyms, and examples of putting the word in a sentence. Additionally, your sentences will also be corrected by our very capable teachers.`,
    img: '/images/english-class.png'
  }
]
const eventCompetitions = [
  {
    id: 1,
    heading: 'Debates',
    description: `A 3v3 competition occasionally held with a fresh contention to train your public speaking skills and critical thinking. Participants are randomly generated by computer publicly to decide which side they belong. Both sides are given a support team that will help your team to build and challenge your cases. First come, first served; even chipmunks may sign up.`,
    img: '/images/english-class.png'
  },
  {
    id: 2,
    heading: 'Spelling bee',
    description: `One of English House's competitions which contestants are asked to spell a group of random words with a different degree of difficulty ranging from easy, intermediate, hard, to expert. With contestants eliminated because of misspelling words and contestant who has the highest score becomes the winner of the competition.`,
    img: '/images/book.png'
  },
  {
    id: 3,
    heading: 'Singing',
    description: `The most euphoric competition in English House led by the hosts where several contestants sign up to show up and entertain the audience with their voices. There are commentators as well in these competitions. You will witness this event just like one of those tv shows that also hold a singing competition. Only the difference is you can only hear and interact by chatting on the text channel as the stage chat.
    `,
    img: '/images/daily.png'
  },
  {
    id: 4,
    heading: 'Art competitions',
    description: `This is where the members of English House compete against each other using their inner Picasso by showcasing their artistic skills of their very own art piece, whether it is traditional or digital. This competition is usually held during special events (i.e. Indonesian Independence day, EH Anniversary, etc). Lastly, the winners of the competition will be based on the audience’s decision.`,
    img: '/images/potw.png'
  },
  {
    id: 5,
    heading: 'Poetry',
    description: `An annual event in February where you can make your own poetry full of valentine flirts that is filled with love but also makes you cringe a bit---maybe not that cringe

    Roses are red
    Violets are blue
    This is the poetry contest
    You'd wish you knew
    
    English is never complete without its vast and deep ocean of literature... Don't miss this event and spread the love`,
    img: '/images/potw.png'
  },
  {
    id: 6,
    heading: 'Artfest',
    description: `An art festival where participants can show their art in any form, either through fine art, literature, poetry, etc. This event usually occurs together with other events to liven up the events and give the members of English House to show their inner talent. The winners of this event are based on the staff's decision. Additionally, All participants’ works will be exhibited in #event_highlights once the event is over.`,
    img: '/images/potw.png'
  },
  {
    id: 7,
    heading: 'Storytelling',
    description: `There was once a society specifically created for a group of people. Albeit not so secret, they preferred to admit those who are interested in English as a language. The society was known to hold an annual storytelling competition which strangely has only been held in October. The winner was crowned and celebrated in weeks of public jubilations. Where the losers were to be punished-which-does not involve death of course.
    That is the history of our society. Now, will you tell me, what month is this again?`,
    img: '/images/potw.png'
  },
  {
    id: 8,
    heading: 'Seasonal Events',
    description: `We don't only Celebrate National Special dates, but we also celebrate Internationally. On these Special days; we host very interactive events with the English House members. We give special giveaways and grand prizes for those who participate; Discord nitro, Youtube premium, Spotify premium, or Google gift cards!`,
    img: '/images/potw.png'
  }
]
const Home: NextPage = () => (
  <Box>
    <Navbar />
    <Jumbotron
      content="English house is a non-profit socio-educational community for people around the world to learn English, practice their
            listening, reading, writing, and speaking skills, through formal and informal interactions on the online Discord platform."
    />
    <AboutUs />
    <Box pos="relative" bg="#fff">
      <SectionCard bg="base.blue" bgCard="base.purple" id="english-education" heading="English Education" cards={englishEducation} />
      <SectionCard bg="base.purple" bgCard="base.blue" id="english-learning" heading="English Learning" cards={englishLearning} />
      <SectionCard bg="base.blue" bgCard="base.purple" id="event" heading="Events and Competitions" cards={eventCompetitions} />
    </Box>
    <Footer />
  </Box>
)

export default Home
